name: auto update branch for mission p3_04_pull
on:
  pull_request_target:
     branches:
       - master
     paths:
       - SOLDOUT_waiting_for_stock.list
     types: opened

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      #- name: Read file content
      #  id: package
      #  uses: juliangruber/read-file-action@v1
      #  with:
      #    path: "./SOLDOUT_waiting_for_stock.list"

      #- name: debug
      #  run: echo "${{ steps.package.outputs.content }}"

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Thanks for your pull request, in particular for  updating the list of sold out item.
            Before incorporating your change could you remove the Excalibur sword out of that file?
            Thanks a lot,
            The bot of the game
            PS; After pushing your modified file, you can directly run "gsh check" to finish the level. 
        #if: contains( ${{ steps.package.outputs.contents }}, 'Excalibur')

